void printEncryptedEnemyField(char field[10][10]);
void fillWithWater(char* field);
void drawMenu();
void printField(char field[10][10]);
void drawWithNotice(char field[10][10], int ships[10]);
char numberToLetter(int number);
int isReady(int ships[10]);
int isThere(int ships[10],int deck);
int isCorrectInput(char symbol);
int isOkToPlace(char i_letter, char i_number, int length,char field[10][10],int vertical);
void putShip(char i_letter,char i_number, int length, char *field, int vertical);
int letterToNumber (char letter);
int numberToNumber (char letter);
int removeShip(int (*field)[10],int number);
void generateRandomField(char *field);
char intNumberToCharLetter (int number);
char intNumberToCharNumber (int number);
void fieldSave1(char yourField[10][10]);
void fieldSave2(char yourField[10][10]);
void fieldSave3(char yourField[10][10]);
void loadFile1(char* field);
void loadFile2(char* field);
void loadFile3(char* field);